# Generated by Django 3.1.1 on 2021-11-02 07:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211102_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
