# Generated by Django 3.1.1 on 2021-11-07 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211102_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
