# Generated by Django 3.1.1 on 2021-10-28 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WishLists',
                'verbose_name_plural': '4. WishLists',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orders', 'verbose_name_plural': '1. Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItems', 'verbose_name_plural': '2. OrderItems'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payments', 'verbose_name_plural': '3. Payments'},
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.wishlist')),
            ],
            options={
                'verbose_name': 'WishListItems',
                'verbose_name_plural': '5. WishListItems',
            },
        ),
    ]
