# Generated by Django 3.1.1 on 2021-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211101_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delevary_charge',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
