# Generated by Django 3.1.1 on 2021-11-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_delevary_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ammount', models.IntegerField()),
                ('activate', models.BooleanField()),
                ('coupon', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
    ]
